# Generated by Django 4.2.6 on 2023-10-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0003_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
