# Generated by Django 4.2.6 on 2023-10-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0005_post_face_emotion_post_text_emotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
