# Generated by Django 4.2.6 on 2023-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0006_remove_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="face_emotion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_emotion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
